substitutions:
  _TAG: ''
steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      apt-get -qq update
      apt-get -qq install unzip
      unzip upstream.zip
      unzip colabtools.zip
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/colab-datalab/datalab:${_TAG}', '-f', 'containers/Dockerfile', '.']
images: ['gcr.io/colab-datalab/datalab:${_TAG}']
timeout: '2400s'
