substitutions:
  _TAG: ''
  _MOVING_TAG: 'latest'
steps:
- id: "unpack"
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      apt-get -qq update
      apt-get -qq install unzip
      unzip colabtools.zip
- id: "build"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t', 'gcr.io/colab-datalab/datalab:${_TAG}',
         '-t', 'gcr.io/colab-datalab/datalab:${_MOVING_TAG}',
         '-f', 'containers/Dockerfile',
         '.']
images:
  - 'gcr.io/colab-datalab/datalab:${_TAG}'
  - 'gcr.io/colab-datalab/datalab:${_MOVING_TAG}'
timeout: '2400s'
options:
  machineType: 'N1_HIGHCPU_32'
